//+------------------------------------------------------------------+
//|                                                DCACloner1_25.mq5 |
//|        Copygram DCA Grid Layer Cloner v1.25 - Hardened Resilience|
//+------------------------------------------------------------------+
#property copyright "Copygram DCA Grid Layer Cloner v1.25 - Hardened Resilience Edition"
#property version   "1.25"
#property strict
#property description "DCA Price Triggered Layers + Dynamic Volatility Switching + Circuit Breakers & Memory Guards"

#include <Trade\Trade.mqh>

//--- Inputs - All Settings at Top
input group "=== CORE STRATEGY INPUTS ==="
input long   InpCopygramMagic       = 0;         // Magic Number for copied orders
input int    InpGridStepPoints      = 100;       // Grid step in points
input int    InpNumLayers           = 0;         // Number of DCA layers
input double InpLayerLot            = 0.01;      // Lot size per layer
input bool   InpUsePending          = true;      // Use pending orders (true) or market (false)
input int    InpSlippage            = 10;        // Slippage in points
input string InpComment             = "DCALayer"; // Order comment
input int    InpMemoryMinutes       = 30;        // Memory for processed orders (minutes)

input group "=== DYNAMIC VOLATILITY MATRIX SETTINGS ==="
input bool   InpEnableAutoTemplate  = true;                 // Enable ATR-based Dynamic Template Switching
input string InpVolFilePath         = "exp_volatility.txt"; // File generated by Python in Common Directory
input int    InpVolCheckInterval    = 5;                    // Volatility File check interval in seconds

input group "=== RISKS & PAUSE SAFETY FAILSAFES ==="
input int    InpEmergencySLPoints   = 350;       // Emergency SL in points (Server-side failsafe)
input double InpMaxAccountDDPercent = 15.0;      // Hard Max Equity Drawdown % (Circuit Breaker)
input bool   InpEnableDailyCleanup  = true;      // Enable daily cleanup
input int    InpDailyCloseHour      = 19;        // Daily close hour (server time)
input int    InpDailyCloseMinute    = 40;        // Daily close minute

input group "=== CLEANUP PARAMETERS ==="
input int    InpMaxDistancePoints   = 500;       // Max distance before cleanup (points)
input double InpMaxLossUSD          = 0.0;       // Max floating loss USD for cleanup (0=disabled)

input group "=== TELEGRAM SANDBOX NEWS MATRIX ==="
input bool   InpEnableNewsClose     = true;               // Enable news-based close/delete
input string InpTriggerFilePath     = "news_trigger.txt";  // Target filename in MT5 Common Directory
input int    InpNewsCheckInterval   = 40;                 // Check interval in seconds
input bool   InpClosePositionsToo   = false;              // Also close open positions (false = only delete pendings)
input int    InpNewsCooldownMinutes = 5;                  // Cooldown after trigger (minutes)

input group "=== MODERN USER VISUAL DISPLAY ==="
input color  InpHeaderColor         = clrLightSeaGreen;
input color  InpTextValueColor      = clrWhite;
input int    InpDashboardX          = 20;                 // Dashboard offset X axis
input int    InpDashboardY          = 40;                 // Dashboard offset Y axis

//+------------------------------------------------------------------+
CTrade trade;
struct ProcessedInfo {
   ulong  ticket;
   ulong  time;
};
ProcessedInfo g_processed[];

struct LiveDCAMatrix {
   ulong     parentTicket;
   int       direction; // 1 = Buy, -1 = Sell
   double    entryPrice;
   double    triggerPrices[];
   bool      layerFired[];
   datetime  registrationTime;
   ulong     childTickets[];
};
LiveDCAMatrix g_dcaBaskets[];

datetime g_lastNewsTrigger  = 0;
datetime g_lastVolCheck     = 0;
int      g_currentVolLevel  = -1;
int      g_failedVolLevel   = -1; // Memory Guard: Tracks failed template loads to prevent 5-second loops
bool     g_systemCircuitPaused = false;

// Forward Declarations
void CheckEquityRecovery();
void CheckGlobalDrawdown();
void CleanupOldProcessed();
void CheckForNewCopygramOrders();
void TrackAndFireMarketGrid();
void CleanupInvalidBaskets();
void CleanupClosedBaskets();
void DailyCleanup();
void CheckNewsTrigger();
void CheckVolatilityAndApplyTemplate();
void UpdateInfoPanel();
void CloseAllPositions();
void DeleteAllPendingOrders();
bool IsProcessed(ulong ticket);
void RegisterDCABasket(ulong ticket, bool isPosition);

//+------------------------------------------------------------------+
int OnInit() {
   ArrayResize(g_processed, 0);
   ArrayResize(g_dcaBaskets, 0);
   trade.SetDeviationInPoints(InpSlippage);
   trade.SetExpertMagicNumber(InpCopygramMagic);
   
   // --- AUTOMATED SERVER RESILIENCE LAYER ---
   uint fillingMode = (uint)SymbolInfoInteger(_Symbol, SYMBOL_FILLING_MODE);
   
   if((fillingMode & SYMBOL_FILLING_FOK) != 0) {
      trade.SetTypeFilling(ORDER_FILLING_FOK);
      Print("Resilience Engine: Configured CTrade to ORDER_FILLING_FOK.");
   }
   else if((fillingMode & SYMBOL_FILLING_IOC) != 0) {
      trade.SetTypeFilling(ORDER_FILLING_IOC);
      Print("Resilience Engine: Configured CTrade to ORDER_FILLING_IOC.");
   }
   else {
      trade.SetTypeFilling(ORDER_FILLING_RETURN);
      Print("Resilience Engine: Configured CTrade to ORDER_FILLING_RETURN.");
   }
   
   EventSetTimer(1);
   Print("Copygram DCA Cloner v1.25 Production Engine initialized successfully.");
   return(INIT_SUCCEEDED);
}

void OnDeinit(const int reason) {
   ObjectsDeleteAll(0, "DCA_DASH_");
   EventKillTimer();
   Print("Cloner EA v1.25 stopped safely.");
}

void OnTick() {
   if(g_systemCircuitPaused) {
      CheckEquityRecovery();
      return;
   }

   CheckGlobalDrawdown();
   CleanupOldProcessed();
   CheckForNewCopygramOrders();
   
   if(!InpUsePending) {
      TrackAndFireMarketGrid();
      CleanupInvalidBaskets();
      CleanupClosedBaskets();
   }
   
   DailyCleanup();
}

void OnTimer() {
   if(InpEnableNewsClose) CheckNewsTrigger();
   if(InpEnableAutoTemplate) CheckVolatilityAndApplyTemplate();
   UpdateInfoPanel();
}

//+------------------------------------------------------------------+
//| HARDENED DYNAMIC TEMPLATE SWITCHING ENGINE                       |
//+------------------------------------------------------------------+
void CheckVolatilityAndApplyTemplate() {
   if(TimeCurrent() - g_lastVolCheck < InpVolCheckInterval) return;
   g_lastVolCheck = TimeCurrent();

   // FIXED: Changed FILE_BIN to FILE_TXT to correctly parse plaintext payloads from Python bridge
   int handle = FileOpen(InpVolFilePath, FILE_READ|FILE_TXT|FILE_ANSI|FILE_COMMON);
   if(handle == INVALID_HANDLE) return;

   string content = "";
   while(!FileIsEnding(handle)) {
      content += FileReadString(handle);
   }
   FileClose(handle);

   if(StringLen(content) == 0) return;

   // Parse payload format: "LEVEL=X,ATR=Y.YY"
   int levelPos = StringFind(content, "LEVEL=");
   if(levelPos < 0) return;

   int newLevel = (int)StringToInteger(StringSubstr(content, levelPos + 6, 1));

   // Circuit Guard: Ignore valid levels that have already failed or match active state
   if(newLevel >= 1 && newLevel <= 5 && newLevel != g_currentVolLevel && newLevel != g_failedVolLevel) {
      string templateName = "";
      switch(newLevel) {
         case 1: templateName = "Level1_UltraLow.tpl"; break;
         case 2: templateName = "Level2_LowNormal.tpl"; break;
         case 3: templateName = "Level3_Moderate.tpl"; break;
         case 4: templateName = "Level4_High.tpl"; break;
         case 5: templateName = "Level5_Extreme.tpl"; break;
      }

      PrintFormat("⚡ Volatility Shift Detected! Level %d -> Applying Template: %s", newLevel, templateName);
      
      if(ChartApplyTemplate(0, templateName)) {
         g_currentVolLevel = newLevel;
         g_failedVolLevel  = -1; // Reset memory guard on success
         PrintFormat("✅ Template %s applied successfully.", templateName);
      } else {
         g_failedVolLevel = newLevel; // Lock memory guard to suppress 5-second retry loops
         PrintFormat("❌ Template Error %d: Failed to apply '%s'. Retries locked for Level %d until new level received.", 
                     GetLastError(), templateName, newLevel);
      }
   }
}

//+------------------------------------------------------------------+
void TrackAndFireMarketGrid() {
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   
   int totalBaskets = ArraySize(g_dcaBaskets);
   for(int i = 0; i < totalBaskets; i++) {
      for(int layer = 0; layer < InpNumLayers; layer++) {
         if(g_dcaBaskets[i].layerFired[layer]) continue;
         
         double trigger = g_dcaBaskets[i].triggerPrices[layer];
         bool shouldFire = (g_dcaBaskets[i].direction == 1) ? (ask <= trigger) : (bid >= trigger);
         
         if(shouldFire) {
            ENUM_ORDER_TYPE orderType = (g_dcaBaskets[i].direction == 1) ? ORDER_TYPE_BUY : ORDER_TYPE_SELL;
            
            bool executionSuccess = false;
            for(int attempt = 1; attempt <= 3; attempt++) {
               if(trade.PositionOpen(_Symbol, orderType, InpLayerLot, 0, 0, 0, InpComment)) {
                  g_dcaBaskets[i].layerFired[layer] = true;
                  g_dcaBaskets[i].childTickets[layer] = trade.ResultDeal();
                  Print("Layer ", layer+1, " executed cleanly for basket path: ", g_dcaBaskets[i].parentTicket);
                  executionSuccess = true;
                  break;
               }
               Print("Trade request execution attempt ", attempt, " failed. Retrying context...");
               Sleep(200);
            }
            
            if(!executionSuccess) {
               Print("CRITICAL: Layer allocation failure occurred after maximum tracking retries.");
            }
         }
      }
   }
}

//+------------------------------------------------------------------+
void CleanupInvalidBaskets() {
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   int total = ArraySize(g_dcaBaskets);
   int newSize = 0;
   
   for(int i = 0; i < total; i++) {
      bool keep = true;
      
      if(!PositionSelectByTicket(g_dcaBaskets[i].parentTicket)) {
         for(int l = 0; l < InpNumLayers; l++) {
            if(g_dcaBaskets[i].layerFired[l] && g_dcaBaskets[i].childTickets[l] > 0) {
               for(int p = PositionsTotal()-1; p >= 0; p--) {
                  ulong pTicket = PositionGetTicket(p);
                  if(pTicket > 0) {
                     if(PositionGetInteger(POSITION_IDENTIFIER) == (long)g_dcaBaskets[i].childTickets[l] || 
                        PositionGetInteger(POSITION_MAGIC) == InpCopygramMagic) {
                        trade.PositionClose(pTicket);
                     }
                  }
               }
            }
         }
         keep = false;
      }
      
      if(keep) {
         double distance = MathAbs(bid - g_dcaBaskets[i].entryPrice) / _Point;
         if(distance > InpMaxDistancePoints) keep = false;
      }
      
      if(InpMaxLossUSD > 0 && keep) {
         double profit = 0;
         if(PositionSelectByTicket(g_dcaBaskets[i].parentTicket)) profit += PositionGetDouble(POSITION_PROFIT);
         for(int l = 0; l < InpNumLayers; l++) {
            if(g_dcaBaskets[i].childTickets[l] > 0) {
               for(int p = PositionsTotal()-1; p >= 0; p--) {
                  ulong pTicket = PositionGetTicket(p);
                  if(pTicket > 0 && PositionGetInteger(POSITION_IDENTIFIER) == (long)g_dcaBaskets[i].childTickets[l]) {
                     profit += PositionGetDouble(POSITION_PROFIT);
                  }
               }
            }
         }
         if(profit < -InpMaxLossUSD) keep = false;
      }
      
      if(keep) {
         if(newSize != i) {
            g_dcaBaskets[newSize].parentTicket = g_dcaBaskets[i].parentTicket;
            g_dcaBaskets[newSize].direction = g_dcaBaskets[i].direction;
            g_dcaBaskets[newSize].entryPrice = g_dcaBaskets[i].entryPrice;
            g_dcaBaskets[newSize].registrationTime = g_dcaBaskets[i].registrationTime;
            
            ArrayResize(g_dcaBaskets[newSize].triggerPrices, InpNumLayers);
            ArrayResize(g_dcaBaskets[newSize].layerFired, InpNumLayers);
            ArrayResize(g_dcaBaskets[newSize].childTickets, InpNumLayers);
            
            for(int l = 0; l < InpNumLayers; l++) {
               g_dcaBaskets[newSize].triggerPrices[l] = g_dcaBaskets[i].triggerPrices[l];
               g_dcaBaskets[newSize].layerFired[l] = g_dcaBaskets[i].layerFired[l];
               g_dcaBaskets[newSize].childTickets[l] = g_dcaBaskets[i].childTickets[l];
            }
         }
         newSize++;
      } else {
         Print("System Matrix safely purged basket context block: ", g_dcaBaskets[i].parentTicket);
      }
   }
   ArrayResize(g_dcaBaskets, newSize);
}

void CleanupClosedBaskets() {
   int total = ArraySize(g_dcaBaskets);
   int newSize = 0;
   for(int i = 0; i < total; i++) {
      if(PositionSelectByTicket(g_dcaBaskets[i].parentTicket)) {
         if(newSize != i) {
            g_dcaBaskets[newSize].parentTicket = g_dcaBaskets[i].parentTicket;
            g_dcaBaskets[newSize].direction = g_dcaBaskets[i].direction;
            g_dcaBaskets[newSize].entryPrice = g_dcaBaskets[i].entryPrice;
            g_dcaBaskets[newSize].registrationTime = g_dcaBaskets[i].registrationTime;
            
            ArrayResize(g_dcaBaskets[newSize].triggerPrices, InpNumLayers);
            ArrayResize(g_dcaBaskets[newSize].layerFired, InpNumLayers);
            ArrayResize(g_dcaBaskets[newSize].childTickets, InpNumLayers);
            
            for(int l = 0; l < InpNumLayers; l++) {
               g_dcaBaskets[newSize].triggerPrices[l] = g_dcaBaskets[i].triggerPrices[l];
               g_dcaBaskets[newSize].layerFired[l] = g_dcaBaskets[i].layerFired[l];
               g_dcaBaskets[newSize].childTickets[l] = g_dcaBaskets[i].childTickets[l];
            }
         }
         newSize++;
      }
   }
   ArrayResize(g_dcaBaskets, newSize);
}

//+------------------------------------------------------------------+
void CheckGlobalDrawdown() {
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double equity = AccountInfoDouble(ACCOUNT_EQUITY);
   
   if(balance <= 0) return;
   double currentDD = ((balance - equity) / balance) * 100.0;
   
   if(currentDD >= InpMaxAccountDDPercent) {
      g_systemCircuitPaused = true;
      Print("CIRCUIT BREAKER TRIGGERED: Account Max Drawdown percentage threshold breached!");
      CloseAllPositions();
      DeleteAllPendingOrders();
      ArrayResize(g_dcaBaskets, 0);
   }
}

void CheckEquityRecovery() {
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double equity = AccountInfoDouble(ACCOUNT_EQUITY);
   double currentDD = ((balance - equity) / balance) * 100.0;
   
   if(currentDD < (InpMaxAccountDDPercent * 0.5)) {
      g_systemCircuitPaused = false;
      Print("Circuit Breaker automatically reset.");
   }
}

//+------------------------------------------------------------------+
void CheckNewsTrigger() {
   if(TimeCurrent() - g_lastNewsTrigger < InpNewsCooldownMinutes * 60) return;
   
   int handle = FileOpen(InpTriggerFilePath, FILE_READ|FILE_BIN|FILE_ANSI|FILE_COMMON);
   if(handle != INVALID_HANDLE) {
      FileClose(handle);
      Print("TELEGRAM MONITOR LOG: Critical News Warning Alert triggered.");
      
      if(InpClosePositionsToo) CloseAllPositions();
      DeleteAllPendingOrders();
      
      FileDelete(InpTriggerFilePath, FILE_COMMON);
      g_lastNewsTrigger = TimeCurrent();
   }
}

void CloseAllPositions() {
   for(int i = PositionsTotal()-1; i >= 0; i--) {
      ulong pTicket = PositionGetTicket(i);
      if(pTicket > 0 && PositionGetInteger(POSITION_MAGIC) == InpCopygramMagic) {
         trade.PositionClose(pTicket);
      }
   }
}

void DeleteAllPendingOrders() {
   for(int i = OrdersTotal()-1; i >= 0; i--) {
      ulong oTicket = OrderGetTicket(i);
      if(oTicket > 0 && OrderGetInteger(ORDER_MAGIC) == InpCopygramMagic) {
         trade.OrderDelete(oTicket);
      }
   }
}

//+------------------------------------------------------------------+
void MarkProcessed(ulong ticket) {
   int size = ArraySize(g_processed);
   ArrayResize(g_processed, size + 1);
   g_processed[size].ticket = ticket;
   g_processed[size].time   = TimeCurrent();
}

void CleanupOldProcessed() {
   int total = ArraySize(g_processed);
   int newSize = 0;
   ulong now = TimeCurrent();
   for(int i = 0; i < total; i++) {
      if((now - g_processed[i].time) < (ulong)InpMemoryMinutes * 60) {
         g_processed[newSize++] = g_processed[i];
      }
   }
   ArrayResize(g_processed, newSize);
}

void CheckForNewCopygramOrders() {
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0) {
         if(PositionGetInteger(POSITION_MAGIC) == InpCopygramMagic && !IsProcessed(ticket)) {
            RegisterDCABasket(ticket, true);
         }
      }
   }
   
   for(int i = OrdersTotal() - 1; i >= 0; i--) {
      ulong ticket = OrderGetTicket(i);
      if(ticket > 0) {
         if(OrderGetInteger(ORDER_MAGIC) == InpCopygramMagic && !IsProcessed(ticket)) {
            RegisterDCABasket(ticket, false);
         }
      }
   }
}

bool IsProcessed(ulong ticket) {
   for(int i = 0; i < ArraySize(g_processed); i++) {
      if(g_processed[i].ticket == ticket) return true;
   }
   return false;
}

//+------------------------------------------------------------------+
void RegisterDCABasket(ulong ticket, bool isPosition) {
   double entryPrice = 0;
   int direction = 0;
   
   if(isPosition) {
      if(!PositionSelectByTicket(ticket)) return;
      entryPrice = PositionGetDouble(POSITION_PRICE_OPEN);
      direction = (PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) ? 1 : -1;
   } else {
      if(!OrderSelect(ticket)) return;
      entryPrice = OrderGetDouble(ORDER_PRICE_OPEN);
      long oType = OrderGetInteger(ORDER_TYPE);
      direction = (oType == ORDER_TYPE_BUY || oType == ORDER_TYPE_BUY_LIMIT || oType == ORDER_TYPE_BUY_STOP) ? 1 : -1;
   }
   
   if(entryPrice == 0) return;
   
   if(InpUsePending) {
      for(int layer = 1; layer <= InpNumLayers; layer++) {
         double offset = layer * InpGridStepPoints * _Point;
         double targetPrice = (direction == 1) ? entryPrice - offset : entryPrice + offset;
         ENUM_ORDER_TYPE pType = (direction == 1) ? ORDER_TYPE_BUY_LIMIT : ORDER_TYPE_SELL_LIMIT;
         
         double hardSL = (direction == 1) ? 
            targetPrice - InpEmergencySLPoints * _Point : targetPrice + InpEmergencySLPoints * _Point;
         
         if(!trade.OrderOpen(_Symbol, pType, InpLayerLot, 0.0, NormalizeDouble(targetPrice, _Digits), 
                             NormalizeDouble(hardSL, _Digits), 0.0, ORDER_TIME_GTC, 0, InpComment)) {
            Print("Failed to place native pending layer: ", layer, " | Error code: ", GetLastError());
         }
      }
   } else {
      int idx = ArraySize(g_dcaBaskets);
      ArrayResize(g_dcaBaskets, idx + 1);
      g_dcaBaskets[idx].parentTicket = ticket;
      g_dcaBaskets[idx].direction = direction;
      g_dcaBaskets[idx].entryPrice = entryPrice;
      g_dcaBaskets[idx].registrationTime = TimeCurrent();
      
      ArrayResize(g_dcaBaskets[idx].triggerPrices, InpNumLayers);
      ArrayResize(g_dcaBaskets[idx].layerFired, InpNumLayers);
      ArrayResize(g_dcaBaskets[idx].childTickets, InpNumLayers);
      
      for(int layer = 0; layer < InpNumLayers; layer++) {
         double offset = (layer + 1) * InpGridStepPoints * _Point;
         g_dcaBaskets[idx].triggerPrices[layer] = (direction == 1) ? entryPrice - offset : entryPrice + offset;
         g_dcaBaskets[idx].layerFired[layer] = false;
         g_dcaBaskets[idx].childTickets[layer] = 0;
      }
   }
   MarkProcessed(ticket);
}

void DailyCleanup() {
   if(!InpEnableDailyCleanup) return;
   MqlDateTime tm;
   TimeToStruct(TimeCurrent(), tm);
   if(tm.hour == InpDailyCloseHour && tm.min == InpDailyCloseMinute) {
      CloseAllPositions();
      DeleteAllPendingOrders();
      ArrayResize(g_dcaBaskets, 0);
      ArrayResize(g_processed, 0);
      Print("Daily cleanup executed.");
   }
}

//+------------------------------------------------------------------+
void UpdateInfoPanel() {
   string labelName = "DCA_DASH_PANEL";
   string levelStr = (g_currentVolLevel > 0) ? StringFormat("VOL LEVEL: %d", g_currentVolLevel) : "VOL LEVEL: INITIALIZING";
   string textStr = StringFormat(" Check if EXP 6 on M1 and aicopier40 are running | %s | ACTIVE BASKETS: %d | STATUS: %s ", 
                     levelStr,
                     ArraySize(g_dcaBaskets), 
                     (g_systemCircuitPaused ? "CRITICAL LOCK" : "OPERATIONAL"));
   
   if(ObjectFind(0, labelName) < 0) {
      ObjectCreate(0, labelName, OBJ_LABEL, 0, 0, 0);
      ObjectSetInteger(0, labelName, OBJPROP_XDISTANCE, InpDashboardX);
      ObjectSetInteger(0, labelName, OBJPROP_YDISTANCE, InpDashboardY);
      ObjectSetInteger(0, labelName, OBJPROP_CORNER, CORNER_LEFT_UPPER);
      ObjectSetString(0, labelName, OBJPROP_FONT, "Trebuchet MS");
      ObjectSetInteger(0, labelName, OBJPROP_FONTSIZE, 11);
   }
   
   ObjectSetString(0, labelName, OBJPROP_TEXT, textStr);
   ObjectSetInteger(0, labelName, OBJPROP_COLOR, (g_systemCircuitPaused ? clrOrangeRed : InpHeaderColor));
}
