name: Compile MT5 EAs
on: [push]

jobs:
  compile:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile MQL5
        uses: fx31337/mql-compile-action@master
        with:
          init-platform: true
          include: '.'
          # Replace this with the actual path to your .mq5 file
          path: 'Experts/MyXAUUSDBot.mq5'
          verbose: true
